// Surya Agencies — Authentic 8-Category Product Catalog
const SAMPLE_PRODUCTS = [
  {
    "id": "arokya-full-cream-500ml",
    "name": "Arokya Full Cream Milk (500ml)",
    "category": "Dairy Products",
    "packSize": "500ml",
    "price": 36,
    "stock": 50,
    "available": 1,
    "description": "Fresh, pasteurized, rich full cream milk with 6.0% fat content for thick curd, tea, and coffee.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "arokya-full-cream-1l",
    "name": "Arokya Full Cream Milk (1 Litre)",
    "category": "Dairy Products",
    "packSize": "1 Litre",
    "price": 70,
    "stock": 40,
    "available": 1,
    "description": "Pure rich wholesome milk with high cream content, ideal for daily family consumption.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "arokya-toned-milk-500ml",
    "name": "Arokya Toned Milk (500ml)",
    "category": "Dairy Products",
    "packSize": "500ml",
    "price": 28,
    "stock": 60,
    "available": 1,
    "description": "Nutritious pasteurized toned milk with 3.0% fat, perfect for balanced everyday health.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "arokya-toned-milk-1l",
    "name": "Arokya Toned Milk (1 Litre)",
    "category": "Dairy Products",
    "packSize": "1 Litre",
    "price": 54,
    "stock": 45,
    "available": 1,
    "description": "Fresh homogenized toned milk packed with essential proteins and calcium.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "arokya-double-toned-500ml",
    "name": "Arokya Double Toned Milk (500ml)",
    "category": "Dairy Products",
    "packSize": "500ml",
    "price": 25,
    "stock": 35,
    "available": 1,
    "description": "Low-fat light double toned milk with 1.5% fat, ideal for fitness and low-calorie diets.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "hatsun-curd-pouch-200g",
    "name": "Hatsun Curd Pouch (200g)",
    "category": "Dairy Products",
    "packSize": "200g",
    "price": 18,
    "stock": 40,
    "available": 1,
    "description": "Traditional thick, creamy dahi made from farm-fresh pasteurized milk.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-curd-pouch-400g",
    "name": "Hatsun Curd Pouch (400g)",
    "category": "Dairy Products",
    "packSize": "400g",
    "price": 34,
    "stock": 50,
    "available": 1,
    "description": "Smooth, naturally set thick curd pouch for everyday meals, curd rice, and raita.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-curd-pouch-1kg",
    "name": "Hatsun Curd Pouch (1kg)",
    "category": "Dairy Products",
    "packSize": "1kg",
    "price": 80,
    "stock": 30,
    "available": 1,
    "description": "Family size pack of rich, thick, and delicious Hatsun farm curd.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-curd-cup-200g",
    "name": "Hatsun Curd Cup (200g)",
    "category": "Dairy Products",
    "packSize": "200g",
    "price": 22,
    "stock": 35,
    "available": 1,
    "description": "Tamper-proof, spill-proof premium tub of naturally cultured creamy curd.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "hatsun-curd-cup-400g",
    "name": "Hatsun Curd Cup (400g)",
    "category": "Dairy Products",
    "packSize": "400g",
    "price": 42,
    "stock": 30,
    "available": 1,
    "description": "Convenient table tub of smooth, creamy curd made with natural active cultures.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "hatsun-fresh-paneer-200g",
    "name": "Hatsun Fresh Paneer (200g)",
    "category": "Dairy Products",
    "packSize": "200g",
    "price": 110,
    "stock": 30,
    "available": 1,
    "description": "Soft, melt-in-mouth cottage cheese made from 100% cow milk, perfect for curries and tikka.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "hatsun-fresh-paneer-500g",
    "name": "Hatsun Fresh Paneer (500g)",
    "category": "Dairy Products",
    "packSize": "500g",
    "price": 260,
    "stock": 20,
    "available": 1,
    "description": "Premium fresh paneer block with high protein and tender texture.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "hatsun-cooking-butter-100g",
    "name": "Hatsun Cooking Butter (100g)",
    "category": "Dairy Products",
    "packSize": "100g",
    "price": 60,
    "stock": 25,
    "available": 1,
    "description": "Unsalted pure white cooking butter for traditional sweets, baking, and clarified ghee.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "hatsun-cooking-butter-500g",
    "name": "Hatsun Cooking Butter (500g)",
    "category": "Dairy Products",
    "packSize": "500g",
    "price": 285,
    "stock": 20,
    "available": 1,
    "description": "Pure churned unsalted dairy butter block for cooking and baking.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "hatsun-table-butter-100g",
    "name": "Hatsun Table Butter (100g)",
    "category": "Dairy Products",
    "packSize": "100g",
    "price": 62,
    "stock": 30,
    "available": 1,
    "description": "Delicious salted golden table butter for morning toasts, parathas, and dosas.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "hatsun-table-butter-500g",
    "name": "Hatsun Table Butter (500g)",
    "category": "Dairy Products",
    "packSize": "500g",
    "price": 295,
    "stock": 15,
    "available": 1,
    "description": "Creamy salted table butter made from fresh dairy cream.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "hatsun-pure-ghee-pouch-200ml",
    "name": "Hatsun Pure Cow Ghee Pouch (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 150,
    "stock": 25,
    "available": 1,
    "description": "Traditional aroma-rich golden granular cow ghee in a convenient flexible pouch.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-pure-ghee-pouch-500ml",
    "name": "Hatsun Pure Cow Ghee Pouch (500ml)",
    "category": "Dairy Products",
    "packSize": "500ml",
    "price": 360,
    "stock": 20,
    "available": 1,
    "description": "100% pure granular aromatic cow ghee for festival sweets and daily meals.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-pure-ghee-jar-500ml",
    "name": "Hatsun Pure Cow Ghee Jar (500ml)",
    "category": "Dairy Products",
    "packSize": "500ml",
    "price": 375,
    "stock": 20,
    "available": 1,
    "description": "Pure cow ghee packed in a reusable, airtight hygienic jar.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-pure-ghee-tin-1l",
    "name": "Hatsun Pure Cow Ghee Tin (1 Litre)",
    "category": "Dairy Products",
    "packSize": "1 Litre",
    "price": 740,
    "stock": 15,
    "available": 1,
    "description": "Premium sealed metal tin of aromatic granular pure cow ghee.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-dairy-whitener-200g",
    "name": "Hatsun Dairy Whitener (200g)",
    "category": "Dairy Products",
    "packSize": "200g",
    "price": 85,
    "stock": 30,
    "available": 1,
    "description": "Instant dissolving dairy milk powder for rich, creamy tea and coffee anywhere.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "hatsun-dairy-whitener-500g",
    "name": "Hatsun Dairy Whitener (500g)",
    "category": "Dairy Products",
    "packSize": "500g",
    "price": 210,
    "stock": 20,
    "available": 1,
    "description": "Fine grade sweet dairy whitener powder made from fresh cow milk.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "hatsun-flavoured-milk-choco",
    "name": "Hatsun Flavoured Milk Chocolate (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 35,
    "stock": 45,
    "available": 1,
    "description": "Creamy chilled milk blended with rich cocoa chocolate flavour in an easy-sip bottle.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "hatsun-flavoured-milk-badam",
    "name": "Hatsun Flavoured Milk Badam (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 35,
    "stock": 45,
    "available": 1,
    "description": "Traditional almond badam infused chilled dairy drink with crushed nut flavor.",
    "image": "/assets/arun-kulfi-maharaj.jpg"
  },
  {
    "id": "hatsun-flavoured-milk-pista",
    "name": "Hatsun Flavoured Milk Pista (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 35,
    "stock": 40,
    "available": 1,
    "description": "Refreshing pistachio green flavoured milk with natural cardamom aroma.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "hatsun-flavoured-milk-strawberry",
    "name": "Hatsun Flavoured Milk Strawberry (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 35,
    "stock": 40,
    "available": 1,
    "description": "Sweet berry flavoured chilled dairy beverage.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "hatsun-lassi-200ml",
    "name": "Hatsun Lassi (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 25,
    "stock": 40,
    "available": 1,
    "description": "Sweet, thick churned refreshing Punjabi-style yogurt drink.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "hatsun-buttermilk-200ml",
    "name": "Hatsun Buttermilk (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 15,
    "stock": 50,
    "available": 1,
    "description": "Spiced cooling traditional moru buttermilk with ginger, curry leaves, and green chillies.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "hatsun-yogurt-shake-strawberry",
    "name": "Hatsun Yogurt Shake Strawberry (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 40,
    "stock": 35,
    "available": 1,
    "description": "Probiotic smooth yogurt shake infused with natural strawberry fruit puree.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "hatsun-yogurt-shake-mango",
    "name": "Hatsun Yogurt Shake Mango (200ml)",
    "category": "Dairy Products",
    "packSize": "200ml",
    "price": 40,
    "stock": 35,
    "available": 1,
    "description": "Delicious thick probiotic mango yogurt shake packed with tropical flavor.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "icone-premium-butterscotch",
    "name": "iCone Premium Butterscotch",
    "category": "Ice Cream Cones",
    "packSize": "110ml",
    "price": 55,
    "stock": 40,
    "available": 1,
    "description": "Crispy waffle cone filled with rich butterscotch ice cream, butterscotch drizzle, and cashew crunchies.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "icone-premium-double-chocolate",
    "name": "iCone Premium Double Chocolate",
    "category": "Ice Cream Cones",
    "packSize": "110ml",
    "price": 60,
    "stock": 45,
    "available": 1,
    "description": "Baked chocolate waffle cone with dark chocolate swirl and chocolate chips.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "icone-premium-blackcurrant",
    "name": "iCone Premium Blackcurrant",
    "category": "Ice Cream Cones",
    "packSize": "110ml",
    "price": 55,
    "stock": 35,
    "available": 1,
    "description": "Tangy exotic blackcurrant swirls in a crunchy cone crowned with berry chocolate disc.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "icone-classic-vanilla",
    "name": "iCone Classic Vanilla",
    "category": "Ice Cream Cones",
    "packSize": "100ml",
    "price": 45,
    "stock": 40,
    "available": 1,
    "description": "Pure Bourbon vanilla ice cream in a crispy wafer cone with chocolate tip.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "icone-classic-strawberry",
    "name": "iCone Classic Strawberry",
    "category": "Ice Cream Cones",
    "packSize": "100ml",
    "price": 45,
    "stock": 35,
    "available": 1,
    "description": "Creamy farm-fresh strawberry cream swirled in a crunchy baked waffle cone.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "icone-choco-coffee",
    "name": "iCone Choco Coffee",
    "category": "Ice Cream Cones",
    "packSize": "110ml",
    "price": 55,
    "stock": 30,
    "available": 1,
    "description": "Aromatic roasted South Indian filter coffee ice cream paired with dark chocolate syrup.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "icone-mini-chocolate",
    "name": "iCone Mini Chocolate",
    "category": "Ice Cream Cones",
    "packSize": "60ml",
    "price": 30,
    "stock": 45,
    "available": 1,
    "description": "Bite-sized crispy mini chocolate cone, ideal for quick treats.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "icone-mini-butterscotch",
    "name": "iCone Mini Butterscotch",
    "category": "Ice Cream Cones",
    "packSize": "60ml",
    "price": 30,
    "stock": 45,
    "available": 1,
    "description": "Miniature crunch cone packed with sweet golden butterscotch.",
    "image": "/assets/arun-spirals-cone.jpg"
  },
  {
    "id": "arun-chocobar-classic",
    "name": "Arun Chocobar Classic",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "65ml",
    "price": 25,
    "stock": 60,
    "available": 1,
    "description": "The iconic classic vanilla ice cream bar dipped in crackling dark chocolate coating.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "arun-chocobar-premium-double-choco",
    "name": "Arun Chocobar Premium Double Choco",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "80ml",
    "price": 40,
    "stock": 50,
    "available": 1,
    "description": "Rich chocolate ice cream core dipped in thick Belgian chocolate shell with almond bits.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "ibar-mango-premium",
    "name": "iBar Mango Premium",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "75ml",
    "price": 35,
    "stock": 45,
    "available": 1,
    "description": "Real Alphonso mango pulp outer crust with a velvety dairy milk centre.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "ibar-raspberry-premium",
    "name": "iBar Raspberry Premium",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "75ml",
    "price": 35,
    "stock": 40,
    "available": 1,
    "description": "Zesty red raspberry fruit crust filled with smooth vanilla cream.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "ibar-choco-feast",
    "name": "iBar Choco Feast",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "90ml",
    "price": 45,
    "stock": 45,
    "available": 1,
    "description": "Heavy decadent chocolate fudge ice cream bar with crispy biscuit balls in chocolate shell.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "kulfi-king-classic-pista",
    "name": "Kulfi King Classic Pista",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "70ml",
    "price": 35,
    "stock": 45,
    "available": 1,
    "description": "Slow simmered malai kulfi enriched with green pistachio nuts and cardamom.",
    "image": "/assets/arun-kulfi-maharaj.jpg"
  },
  {
    "id": "kulfi-king-badam",
    "name": "Kulfi King Badam",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "70ml",
    "price": 35,
    "stock": 40,
    "available": 1,
    "description": "Traditional royal almond kulfi stick with authentic texture.",
    "image": "/assets/arun-kulfi-maharaj.jpg"
  },
  {
    "id": "kulfi-king-malai",
    "name": "Kulfi King Malai",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "70ml",
    "price": 35,
    "stock": 40,
    "available": 1,
    "description": "Pure thick clotted rabri malai kulfi stick with classic richness.",
    "image": "/assets/arun-kulfi-maharaj.jpg"
  },
  {
    "id": "likstick-mango-ice-lolly",
    "name": "Likstick Mango Ice Lolly",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "60ml",
    "price": 15,
    "stock": 50,
    "available": 1,
    "description": "Refreshing juicy frozen tropical mango water ice lolly.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "likstick-grape-ice-lolly",
    "name": "Likstick Grape Ice Lolly",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "60ml",
    "price": 15,
    "stock": 50,
    "available": 1,
    "description": "Sweet and tangy purple concord grape ice candy stick.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "likstick-orange-ice-lolly",
    "name": "Likstick Orange Ice Lolly",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "60ml",
    "price": 15,
    "stock": 50,
    "available": 1,
    "description": "Cooling tangy orange fruit juice ice pop.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "yummy-bear-vanilla-stick",
    "name": "Yummy Bear Vanilla Stick",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "55ml",
    "price": 20,
    "stock": 40,
    "available": 1,
    "description": "Fun bear-shaped creamy vanilla ice cream pop designed for kids.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "yummy-bear-chocolate-stick",
    "name": "Yummy Bear Chocolate Stick",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "55ml",
    "price": 20,
    "stock": 40,
    "available": 1,
    "description": "Playful bear-shaped milk chocolate ice cream bar.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "cotton-candy-stick",
    "name": "Cotton Candy Stick",
    "category": "Ice Cream Bars & Sticks",
    "packSize": "65ml",
    "price": 30,
    "stock": 35,
    "available": 1,
    "description": "Dual-swirled pink and sky-blue sweet cotton candy flavour ice cream bar.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "classic-vanilla-cup-50ml",
    "name": "Classic Vanilla Cup (50ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "50ml",
    "price": 15,
    "stock": 60,
    "available": 1,
    "description": "Pure smooth vanilla cup, convenient mini portion with spoon.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "classic-vanilla-cup-100ml",
    "name": "Classic Vanilla Cup (100ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "100ml",
    "price": 25,
    "stock": 60,
    "available": 1,
    "description": "All-time favourite rich dairy vanilla ice cream cup.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "classic-strawberry-cup-50ml",
    "name": "Classic Strawberry Cup (50ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "50ml",
    "price": 15,
    "stock": 50,
    "available": 1,
    "description": "Refreshing sweet strawberry ice cream cup in small serving.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "classic-strawberry-cup-100ml",
    "name": "Classic Strawberry Cup (100ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "100ml",
    "price": 25,
    "stock": 50,
    "available": 1,
    "description": "Silky smooth strawberry ice cream cup made from real milk.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "classic-chocolate-cup-100ml",
    "name": "Classic Chocolate Cup (100ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "100ml",
    "price": 30,
    "stock": 55,
    "available": 1,
    "description": "Creamy cocoa chocolate ice cream cup with rich chocolate taste.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "premium-butterscotch-cup-100ml",
    "name": "Premium Butterscotch Cup (100ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "100ml",
    "price": 35,
    "stock": 45,
    "available": 1,
    "description": "Sweet butterscotch ice cream cup loaded with crunchy cashew pralines.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "premium-blackcurrant-cup-100ml",
    "name": "Premium Blackcurrant Cup (100ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "100ml",
    "price": 35,
    "stock": 40,
    "available": 1,
    "description": "Tangy exotic blackcurrant berry cup with rich fruit flavour.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "premium-kesar-pista-cup-100ml",
    "name": "Premium Kesar Pista Cup (100ml)",
    "category": "Ice Cream Cups & Duets",
    "packSize": "100ml",
    "price": 40,
    "stock": 40,
    "available": 1,
    "description": "Royal saffron kesar ice cream cup with real sliced pistachios.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "duet-vanilla-raspberry",
    "name": "Duet Vanilla & Raspberry Cup",
    "category": "Ice Cream Cups & Duets",
    "packSize": "110ml",
    "price": 40,
    "stock": 35,
    "available": 1,
    "description": "Two-in-one twin dessert cup pairing smooth vanilla with zesty raspberry.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "duet-vanilla-mango",
    "name": "Duet Vanilla & Mango Cup",
    "category": "Ice Cream Cups & Duets",
    "packSize": "110ml",
    "price": 40,
    "stock": 35,
    "available": 1,
    "description": "Harmonious duo of creamy vanilla and tropical sweet Alphonso mango.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "duet-chocolate-mint",
    "name": "Duet Chocolate & Mint Cup",
    "category": "Ice Cream Cups & Duets",
    "packSize": "110ml",
    "price": 40,
    "stock": 30,
    "available": 1,
    "description": "Refreshing cool green mint ice cream coupled with decadent dark chocolate.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "ice-cream-sandwich-vanilla",
    "name": "Ice Cream Sandwich Vanilla",
    "category": "Ice Cream Novelties & Slices",
    "packSize": "90ml",
    "price": 35,
    "stock": 35,
    "available": 1,
    "description": "Thick slab of creamy vanilla ice cream between two soft chocolate cookies.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "ice-cream-sandwich-chocolate",
    "name": "Ice Cream Sandwich Chocolate",
    "category": "Ice Cream Novelties & Slices",
    "packSize": "90ml",
    "price": 40,
    "stock": 35,
    "available": 1,
    "description": "Double chocolate sandwich with chocolate ice cream in chocolate cookie biscuits.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "cassata-premium-slice",
    "name": "Cassata Premium Slice",
    "category": "Ice Cream Novelties & Slices",
    "packSize": "100g",
    "price": 65,
    "stock": 40,
    "available": 1,
    "description": "Multi-layer sponge cake slice with strawberry, vanilla, and pistachio ice cream garnished with cashew praline.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "cassata-ball",
    "name": "Cassata Ball",
    "category": "Ice Cream Novelties & Slices",
    "packSize": "110ml",
    "price": 55,
    "stock": 30,
    "available": 1,
    "description": "Spherical ball of three layered ice cream flavours filled with a dry fruit core.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "arun-bites-kesar-peda",
    "name": "Arun Bites Kesar Peda Fusion Pack",
    "category": "Ice Cream Novelties & Slices",
    "packSize": "120ml (6 Pcs)",
    "price": 75,
    "stock": 25,
    "available": 1,
    "description": "Traditional Indian sweet fusion bite-sized ice cream cubes coated in saffron chocolate.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "arun-bites-motichoor",
    "name": "Arun Bites Motichoor Fusion Pack",
    "category": "Ice Cream Novelties & Slices",
    "packSize": "120ml (6 Pcs)",
    "price": 75,
    "stock": 25,
    "available": 1,
    "description": "Bite-sized festive ice cream morsels infused with golden motichoor ladoo pearls.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "arun-bites-kaju-katli",
    "name": "Arun Bites Kaju Katli Fusion Pack",
    "category": "Ice Cream Novelties & Slices",
    "packSize": "120ml (6 Pcs)",
    "price": 85,
    "stock": 25,
    "available": 1,
    "description": "Rich cashew kaju katli fudge blended into gourmet ice cream bite cubes.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "chocolate-fudge-sundae-cup",
    "name": "Chocolate Fudge Sundae Cup",
    "category": "Sundaes & In-Store Specials",
    "packSize": "140ml",
    "price": 60,
    "stock": 35,
    "available": 1,
    "description": "Rich vanilla ice cream drenched in warm gooey chocolate fudge and roasted peanuts.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "butterscotch-crunch-sundae-cup",
    "name": "Butterscotch Crunch Sundae Cup",
    "category": "Sundaes & In-Store Specials",
    "packSize": "140ml",
    "price": 60,
    "stock": 35,
    "available": 1,
    "description": "Butterscotch ice cream sundae layered with caramel toffee syrup and golden cashew nut crunch.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "mango-jelly-sundae-cup",
    "name": "Mango Jelly Sundae Cup",
    "category": "Sundaes & In-Store Specials",
    "packSize": "140ml",
    "price": 60,
    "stock": 30,
    "available": 1,
    "description": "Alphonso mango cream layered with chewy mango fruit jelly chunks and puree.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "strawberry-twist-sundae-cup",
    "name": "Strawberry Twist Sundae Cup",
    "category": "Sundaes & In-Store Specials",
    "packSize": "140ml",
    "price": 60,
    "stock": 30,
    "available": 1,
    "description": "Strawberry ripple sundae topped with berry syrup and white chocolate drops.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "cookie-cream-sundae-cup",
    "name": "Cookie Cream Sundae Cup",
    "category": "Sundaes & In-Store Specials",
    "packSize": "140ml",
    "price": 65,
    "stock": 30,
    "available": 1,
    "description": "Smooth sweet cream loaded with crushed dark chocolate sandwich cookies and chocolate drizzle.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "classic-vanilla-tub-1l",
    "name": "Classic Vanilla Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 180,
    "stock": 25,
    "available": 1,
    "description": "Large family party tub of classic pure vanilla cream dessert.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "classic-strawberry-tub-1l",
    "name": "Classic Strawberry Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 180,
    "stock": 20,
    "available": 1,
    "description": "Creamy refreshing strawberry ice cream family dessert tub.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "classic-chocolate-tub-1l",
    "name": "Classic Chocolate Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 210,
    "stock": 25,
    "available": 1,
    "description": "Decadent rich milk chocolate family dessert tub.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "premium-butterscotch-tub-1l",
    "name": "Premium Butterscotch Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 240,
    "stock": 25,
    "available": 1,
    "description": "Creamy rich butterscotch dessert tub packed with roasted cashew nut crunchies.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "premium-blackcurrant-tub-1l",
    "name": "Premium Blackcurrant Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 250,
    "stock": 20,
    "available": 1,
    "description": "Gourmet blackcurrant berry tub with delicious fruit ripples.",
    "image": "/assets/arun-vanilla-cup.jpg"
  },
  {
    "id": "premium-kesar-pista-tub-1l",
    "name": "Premium Kesar Pista Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 280,
    "stock": 20,
    "available": 1,
    "description": "Royal saffron kesar ice cream family tub loaded with Iranian pistachios and almonds.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "premium-mango-alfonso-tub-1l",
    "name": "Premium Mango Alfonso Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 240,
    "stock": 20,
    "available": 1,
    "description": "Luscious tropical Ratnagiri Alphonso mango pulp churned into velvety ice cream.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "exotic-red-velvet-tub-1l",
    "name": "Exotic Red Velvet Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 320,
    "stock": 15,
    "available": 1,
    "description": "Cream cheese ice cream folded with soft crimson red velvet cake crumbs and chocolate ripples.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "exotic-brownie-banoffee-tub-1l",
    "name": "Exotic Brownie Banoffee Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 330,
    "stock": 15,
    "available": 1,
    "description": "Banana toffee ice cream mixed with chewy chocolate fudge brownie chunks.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "exotic-salted-caramel-tub-1l",
    "name": "Exotic Salted Caramel Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 320,
    "stock": 15,
    "available": 1,
    "description": "Sweet and buttery caramelized cream accented with gourmet sea salt crystals.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "exotic-jackfruit-tub-1l",
    "name": "Exotic Jackfruit Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 310,
    "stock": 15,
    "available": 1,
    "description": "Traditional ripe sweet jackfruit (chakka) flavour blended into luscious dairy cream.",
    "image": "/assets/arun-matka-kulfi.jpg"
  },
  {
    "id": "exotic-blueberry-cheesecake-tub-1l",
    "name": "Exotic Blueberry Cheesecake Tub (1L)",
    "category": "Family Tubs & Packs",
    "packSize": "1 Litre",
    "price": 340,
    "stock": 15,
    "available": 1,
    "description": "Rich New York style cream cheesecake ice cream swirled with wild Canadian blueberry compote.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "signature-black-forest-cake",
    "name": "Signature Black Forest Ice Cream Cake",
    "category": "Ice Cream Cakes",
    "packSize": "500g",
    "price": 390,
    "stock": 15,
    "available": 1,
    "description": "Chocolate sponge cake base layered with vanilla ice cream, dark chocolate curls, and red cherry compote.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "signature-butterscotch-delight-cake",
    "name": "Signature Butterscotch Delight Ice Cream Cake",
    "category": "Ice Cream Cakes",
    "packSize": "500g",
    "price": 390,
    "stock": 15,
    "available": 1,
    "description": "Golden butterscotch cake with butterscotch crunch layers and toffee caramel glaze.",
    "image": "/assets/arun-butterscotch-tub.jpg"
  },
  {
    "id": "signature-choco-brownie-cake",
    "name": "Signature Choco-Brownie Ice Cream Cake",
    "category": "Ice Cream Cakes",
    "packSize": "550g",
    "price": 430,
    "stock": 15,
    "available": 1,
    "description": "Fudge brownie base topped with decadent Belgian chocolate ice cream and dark chocolate truffle ganache.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "signature-cassata-celebration-cake",
    "name": "Signature Cassata Celebration Ice Cream Cake",
    "category": "Ice Cream Cakes",
    "packSize": "500g",
    "price": 420,
    "stock": 12,
    "available": 1,
    "description": "Royal 3-tier celebratory ice cream cake featuring strawberry, pistachio, and vanilla with cashew nuts.",
    "image": "/assets/arun-cassatta.jpg"
  },
  {
    "id": "signature-mango-magic-cake",
    "name": "Signature Mango Magic Ice Cream Cake",
    "category": "Ice Cream Cakes",
    "packSize": "500g",
    "price": 410,
    "stock": 12,
    "available": 1,
    "description": "Exotic tropical Alphonso mango ice cream cake with mango glaze and vanilla sponge.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "signature-strawberry-cream-cake",
    "name": "Signature Strawberry Cream Ice Cream Cake",
    "category": "Ice Cream Cakes",
    "packSize": "500g",
    "price": 390,
    "stock": 12,
    "available": 1,
    "description": "Tender pink strawberry ice cream cake adorned with white chocolate flakes.",
    "image": "/assets/arun-trio.jpg"
  },
  {
    "id": "ice-cream-cake-mini-log-choco",
    "name": "Ice Cream Cake Mini Log Chocolate",
    "category": "Ice Cream Cakes",
    "packSize": "250g",
    "price": 220,
    "stock": 20,
    "available": 1,
    "description": "Individual swiss roll style chocolate ice cream dessert log coated in dark chocolate.",
    "image": "/assets/arun-chocobar.jpg"
  },
  {
    "id": "ice-cream-cake-mini-log-vanilla",
    "name": "Ice Cream Cake Mini Log Vanilla",
    "category": "Ice Cream Cakes",
    "packSize": "250g",
    "price": 220,
    "stock": 20,
    "available": 1,
    "description": "Delicate vanilla sponge log filled with pure dairy vanilla ice cream and white chocolate drizzle.",
    "image": "/assets/arun-cassatta.jpg"
  }
];

module.exports = {
  SAMPLE_PRODUCTS
};
